// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE2DgSJqq3uiuTEll7RpewjDUq0yEvvWU',
    appId: '1:752351836162:web:82ad452bd2bc90d591cf1b',
    messagingSenderId: '752351836162',
    projectId: 'certosec-e58dd',
    authDomain: 'certosec-e58dd.firebaseapp.com',
    storageBucket: 'certosec-e58dd.firebasestorage.app',
    measurementId: 'G-6TP6VVPC0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz_unkHf0kwVexCox52Auhn1F9ZypDEeE',
    appId: '1:752351836162:android:1c22522b5b2427b691cf1b',
    messagingSenderId: '752351836162',
    projectId: 'certosec-e58dd',
    storageBucket: 'certosec-e58dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9MOcEvx26ZYsbb9dn0knXRHVptJJNkW4',
    appId: '1:752351836162:ios:e8ad096ed7259ffe91cf1b',
    messagingSenderId: '752351836162',
    projectId: 'certosec-e58dd',
    storageBucket: 'certosec-e58dd.firebasestorage.app',
    iosBundleId: 'com.example.certosec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9MOcEvx26ZYsbb9dn0knXRHVptJJNkW4',
    appId: '1:752351836162:ios:e8ad096ed7259ffe91cf1b',
    messagingSenderId: '752351836162',
    projectId: 'certosec-e58dd',
    storageBucket: 'certosec-e58dd.firebasestorage.app',
    iosBundleId: 'com.example.certosec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE2DgSJqq3uiuTEll7RpewjDUq0yEvvWU',
    appId: '1:752351836162:web:82ad452bd2bc90d591cf1b',
    messagingSenderId: '752351836162',
    projectId: 'certosec-e58dd',
    authDomain: 'certosec-e58dd.firebaseapp.com',
    storageBucket: 'certosec-e58dd.firebasestorage.app',
    measurementId: 'G-6TP6VVPC0Q',
  );

}